// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ../../../public/room.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GroupProps } from "@react-three/fiber";

export function Room(props: GroupProps) {
  const { nodes, materials } = useGLTF('/glbs/room.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube024.geometry} material={materials['FFCC88.003']} />
      {/* <mesh geometry={nodes.Plane004_Plane010.geometry} material={materials['795548.002']} /> */}
      <mesh geometry={nodes.Plane003_Plane008.geometry} material={materials.FFFFFF} />
      <mesh geometry={nodes.Cube002_Cube003.geometry} material={materials['039BE5']} />
      {/* <mesh geometry={nodes.Cube001_Cube002.geometry} material={materials['F44336.006']} /> */}
      {/* <mesh geometry={nodes['Circle005-Mesh'].geometry} material={materials['455A64.002']} />
      <mesh geometry={nodes['Circle005-Mesh_1'].geometry} material={materials['039BE5']} />
      <mesh geometry={nodes['Circle005-Mesh_2'].geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes['Circle005-Mesh_3'].geometry} material={materials.F44336} />
      <mesh geometry={nodes['Circle005-Mesh_4'].geometry} material={materials['4CAF50.001']} />
      <mesh geometry={nodes['Circle005-Mesh_5'].geometry} material={materials['78909C']} /> */}
      <mesh geometry={nodes['flower_01_Cube000-Mesh'].geometry} material={materials['795548.001']} />
      <mesh geometry={nodes['flower_01_Cube000-Mesh_1'].geometry} material={materials['F8BBD0.001']} />
      {/* <mesh geometry={nodes['Cylinder-Mesh'].geometry} material={materials.Imagetexture} />
      <mesh geometry={nodes['Cylinder-Mesh_1'].geometry} material={materials['DD9944.004']} /> */}
      <mesh geometry={nodes['Plane002_Plane009-Mesh'].geometry} material={materials['FF9800.001']} />
      <mesh geometry={nodes['Plane002_Plane009-Mesh_1'].geometry} material={materials['FFFFFF.008']} />
      <mesh geometry={nodes['Cube036_Cube037-Mesh'].geometry} material={materials['FFFFFF.012']} />
      <mesh geometry={nodes['Cube036_Cube037-Mesh_1'].geometry} material={materials['1A1A1A.009']} />
      <mesh geometry={nodes['Cube036_Cube037-Mesh_2'].geometry} material={materials['F8BBD0.002']} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh'].geometry} material={materials['F44336.008']} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh_1'].geometry} material={materials['FFFFFF.011']} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh_2'].geometry} material={materials['1A1A1A.008']} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh_3'].geometry} material={materials['FF9800.005']} />
      <mesh geometry={nodes['Cube035_Cube034-Mesh_4'].geometry} material={materials['455A64.004']} />
      <mesh geometry={nodes['pine_tree_01_Circle-Mesh'].geometry} material={materials['8BC34A.006']} />
      <mesh geometry={nodes['pine_tree_01_Circle-Mesh_1'].geometry} material={materials['795548.010']} />
      <mesh geometry={nodes['pine_tree_01_Circle-Mesh_2'].geometry} material={materials['4CAF50.004']} />
      <mesh geometry={nodes['palm_tree_01-Mesh'].geometry} material={materials['4CAF50.001-2']} />
      <mesh geometry={nodes['palm_tree_01-Mesh_1'].geometry} material={materials['795548.009']} />
      <mesh geometry={nodes['palm_tree_01-Mesh_2'].geometry} material={materials['DD9944.005']} />
      <mesh geometry={nodes['apple_tree_01_Cube001-Mesh'].geometry} material={materials['F44336.007']} />
      <mesh geometry={nodes['apple_tree_01_Cube001-Mesh_1'].geometry} material={materials['8BC34A.004']} />
      <mesh geometry={nodes['apple_tree_01_Cube001-Mesh_2'].geometry} material={materials['795548.008']} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh'].geometry} material={materials['FF5722.004']} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_1'].geometry} material={materials['FFCC88.002']} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_2'].geometry} material={materials['CFD8DC.002']} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_3'].geometry} material={materials['FFEB3B.004']} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_4'].geometry} material={materials['78909C.001']} />
      <mesh geometry={nodes['campfire_01_Plane003-Mesh_5'].geometry} material={materials['795548.007']} />
      <mesh geometry={nodes['Dinosaurs_01_Cube019-Mesh'].geometry} material={materials['8BC34A.003']} />
      <mesh geometry={nodes['Dinosaurs_01_Cube019-Mesh_1'].geometry} material={materials['FFFFFF.010']} />
      <mesh geometry={nodes['Dinosaurs_01_Cube019-Mesh_2'].geometry} material={materials['1A1A1A.007']} />
      <mesh geometry={nodes['Dinosaurs_01_Cube019-Mesh_3'].geometry} material={materials['4CAF50.003']} />
      <mesh geometry={nodes['Bush_01_Icosphere001-Mesh'].geometry} material={materials['795548.006']} />
      <mesh geometry={nodes['Bush_01_Icosphere001-Mesh_1'].geometry} material={materials['9C27B0.001']} />
      <mesh geometry={nodes['Bush_01_Icosphere001-Mesh_2'].geometry} material={materials['F06292.004']} />
      <mesh geometry={nodes['Bush_01_Icosphere001-Mesh_3'].geometry} material={materials['4CAF50.002']} />
      <mesh geometry={nodes['fish_01_Cube003-Mesh'].geometry} material={materials['FFEB3B.003']} />
      <mesh geometry={nodes['fish_01_Cube003-Mesh_1'].geometry} material={materials['1A1A1A.006']} />
      <mesh geometry={nodes['fish_01_Cube003-Mesh_2'].geometry} material={materials['FF9800.004']} />
      <mesh geometry={nodes['fish_01_Cube003-Mesh_3'].geometry} material={materials['FFFFFF.009']} />
      {/* <mesh geometry={nodes['sun_01_Sphere-Mesh'].geometry} material={materials['FF9800.003']} />
      <mesh geometry={nodes['sun_01_Sphere-Mesh_1'].geometry} material={materials['FF5722.003']} /> */}
      <mesh geometry={nodes['Circle004-Mesh'].geometry} material={materials['FFFFFF.008']} />
      <mesh geometry={nodes['Circle004-Mesh_1'].geometry} material={materials['1A1A1A.005']} />
      <mesh geometry={nodes['Circle004-Mesh_2'].geometry} material={materials['DD9944.004-2']} />
      <mesh geometry={nodes['Circle002-Mesh'].geometry} material={materials['FFFFFF.007']} />
      <mesh geometry={nodes['Circle002-Mesh_1'].geometry} material={materials['039BE5.003']} />
      <mesh geometry={nodes['Circle-Mesh'].geometry} material={materials['F44336.006']} />
      <mesh geometry={nodes['Circle-Mesh_1'].geometry} material={materials['FFFFFF.006']} />
      <mesh geometry={nodes['Circle-Mesh_2'].geometry} material={materials['795548.005']} />
      <mesh geometry={nodes['Circle-Mesh_3'].geometry} material={materials['DD9944.003']} />
      <mesh geometry={nodes['Circle010-Mesh'].geometry} material={materials['F44336.005']} />
      <mesh geometry={nodes['Circle010-Mesh_1'].geometry} material={materials['FFFFFF.005']} />
      {/* <mesh geometry={nodes['Icosphere015_Icosphere018-Mesh'].geometry} material={materials['673AB7.001']} />
      <mesh geometry={nodes['Icosphere015_Icosphere018-Mesh_1'].geometry} material={materials['4CAF50.001']} /> */}
      <mesh geometry={nodes['Circle007-Mesh'].geometry} material={materials['FFFFFF.004']} />
      <mesh geometry={nodes['Circle007-Mesh_1'].geometry} material={materials['F06292.003']} />
      <mesh geometry={nodes['Plane006-Mesh'].geometry} material={materials['F44336.004']} />
      <mesh geometry={nodes['Plane006-Mesh_1'].geometry} material={materials['FFCC88.001']} />
      <mesh geometry={nodes['Plane006-Mesh_2'].geometry} material={materials['FFEB3B.002']} />
      <mesh geometry={nodes['Plane006-Mesh_3'].geometry} material={materials['FF5722.002']} />
      <mesh geometry={nodes['Circle003_Circle004-Mesh'].geometry} material={materials['8BC34A.002']} />
      <mesh geometry={nodes['Circle003_Circle004-Mesh_1'].geometry} material={materials['FF9800.002']} />
      <mesh geometry={nodes['Circle003_Circle004-Mesh_2'].geometry} material={materials['FF5722.001']} />
      <mesh geometry={nodes['Circle003_Circle004-Mesh_3'].geometry} material={materials['DD9944.002']} />
      <mesh geometry={nodes['Circle003_Circle004-Mesh_4'].geometry} material={materials['F44336.003']} />
      <mesh geometry={nodes['Circle003_Circle004-Mesh_5'].geometry} material={materials['795548.004']} />
      <mesh geometry={nodes['Cube028_Cube030-Mesh'].geometry} material={materials['FFFFFF.003']} />
      <mesh geometry={nodes['Cube028_Cube030-Mesh_1'].geometry} material={materials['1A1A1A.004']} />
      <mesh geometry={nodes['Cube028_Cube030-Mesh_2'].geometry} material={materials['F06292.002']} />
      <mesh geometry={nodes['Cube026-Mesh'].geometry} material={materials['455A64.003']} />
      <mesh geometry={nodes['Cube026-Mesh_1'].geometry} material={materials['F06292.001']} />
      <mesh geometry={nodes['Cube026-Mesh_2'].geometry} material={materials['DD9944.001']} />
      <mesh geometry={nodes['Cube026-Mesh_3'].geometry} material={materials['FFFFFF.002']} />
      <mesh geometry={nodes['Cube026-Mesh_4'].geometry} material={materials['1A1A1A.003']} />
      <mesh geometry={nodes['Cube026-Mesh_5'].geometry} material={materials['795548.003']} />
      {/* <mesh geometry={nodes['Cube034_Cube035-Mesh'].geometry} material={materials['FFFFFF.001']} />
      <mesh geometry={nodes['Cube034_Cube035-Mesh_1'].geometry} material={materials['1A1A1A.002']} />
      <mesh geometry={nodes['Cube034_Cube035-Mesh_2'].geometry} material={materials['039BE5.002']} /> */}
      {/* <mesh geometry={nodes['car_01_Cube004-Mesh'].geometry} material={materials['455A64.002']} />
      <mesh geometry={nodes['car_01_Cube004-Mesh_1'].geometry} material={materials['F44336.002']} />
      <mesh geometry={nodes['car_01_Cube004-Mesh_2'].geometry} material={materials['CFD8DC.001']} />
      <mesh geometry={nodes['car_01_Cube004-Mesh_3'].geometry} material={materials['FFEB3B.001']} />
      <mesh geometry={nodes['car_01_Cube004-Mesh_4'].geometry} material={materials['1A1A1A.001']} />
      <mesh geometry={nodes['car_01_Cube004-Mesh_5'].geometry} material={materials['795548.002']} />
      <mesh geometry={nodes['car_01_Cube004-Mesh_6'].geometry} material={materials['039BE5.001']} /> */}
      <mesh geometry={nodes['flower_01_Cube007-Mesh'].geometry} material={materials['8BC34A.001']} />
      <mesh geometry={nodes['flower_01_Cube007-Mesh_1'].geometry} material={materials['FF9800.001']} />
      <mesh geometry={nodes['flower_01_Cube007-Mesh_2'].geometry} material={materials['455A64.001']} />
      <mesh geometry={nodes['flower_01_Cube007-Mesh_3'].geometry} material={materials['F44336.001']} />
      <mesh geometry={nodes['flower_01_Cube007-Mesh_4'].geometry} material={materials['795548.001']} />
      <mesh geometry={nodes['flower_01_Cube007-Mesh_5'].geometry} material={materials['F8BBD0.001']} />
      {/* <mesh geometry={nodes['Cube003_Cube006-Mesh'].geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes['Cube003_Cube006-Mesh_1'].geometry} material={materials['78909C']} />
      <mesh geometry={nodes['Cube003_Cube006-Mesh_2'].geometry} material={materials.FFFFFF} /> */}
      {/* <mesh geometry={nodes['Cube005-Mesh'].geometry} material={materials['795548']} />
      <mesh geometry={nodes['Cube005-Mesh_1'].geometry} material={materials['455A64']} />
      <mesh geometry={nodes['Cube005-Mesh_2'].geometry} material={materials['78909C']} />
      <mesh geometry={nodes['Cube004_Cube-Mesh'].geometry} material={materials['78909C']} />
      <mesh geometry={nodes['Cube004_Cube-Mesh_1'].geometry} material={materials['795548']} />
      <mesh geometry={nodes['Cube004_Cube-Mesh_2'].geometry} material={materials['455A64']} /> */}
      <mesh geometry={nodes['Cube_Cube001-Mesh'].geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes['Cube_Cube001-Mesh_1'].geometry} material={materials['78909C']} />
      <mesh geometry={nodes['Plane-Mesh'].geometry} material={materials['FFEB3B.002-2']} />
      <mesh geometry={nodes['Plane-Mesh_1'].geometry} material={materials['795548.004-2']} />
    </group>
  )
}

useGLTF.preload('/room.glb')
